### PR TITLE
Unit testing initial requirements

### PR DESCRIPTION
**Pull request by MasonR03**
Implemented unit tests in jest for required functions (generateChartImg.js, chartStorage.js, sortPoints.js), utilizing JSDOM testing library. All tests pass using 'npm test'

### CODE REVIEW

**Review by OctoBrownie — APPROVED** [review]
Looks fine, nice AAA pattern usage.

**Review by mannydoorman — CHANGES_REQUESTED** [review]
nice work, unit testing passes correctly and is organized well ! However, the e2e tests from a separate PR branch are also included in this one. Before merging, it we be good to remove those files for this specific unit testing branch. thanks

**Comment by MasonR03** [comment]
> nice work, unit testing passes correctly and is organized well ! However, the e2e tests from a separate PR branch are also included in this one. Before merging, it we be good to remove those files for this specific unit testing branch. thanks

Good catch and noted, removing the e2e stuff now so we have a separate branch for each!

**Review by CapnCheesy — APPROVED** [review]
Unit tests look good and well formatted, and the e2e tests were successfully removed from this feature branch.

**Review by mannydoorman — COMMENTED** [review]
nice

**Review by mannydoorman — APPROVED** [review]

**Pull request merged**
